import { Inter } from "next/font/google";
import "./globals.css";
import { IoIosArrowBack } from "react-icons/io";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Professional Portfolio of Akshay Bisht.",
  description: "Personal Professional Portfolio Generated by next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="absolute left-4 top-4 text-4xl">
          <Link href="/">
            <IoIosArrowBack />
          </Link>
        </div>
        {children}
      </body>
    </html>
  );
}
